name: E2E workflow 

on:
  repository_dispatch:
    types:
      - test-flutter-code
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # - name: Trigger Source Repository Workflow
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.PAT }} # Replace with your PAT
      #     repository: Hassanajmalcowlar/test-flutter-application
      #     event-type: build-and-test
      - name: 'Set Flutter 3.10.6'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          package: system-images;android-30;google_apis;x86_64
          build-tools-version: 30.0.3
          emulator-name: emulator

      - name: Start Emulator
        run: |
          emulator -avd emulator -no-window -no-snapshot -noaudio -gpu off -verbose &
          android-wait-for-emulator
          adb shell input keyevent 82 &
          sleep 10

      - name: Navigate to Submodule Directory
        run: |
          git submodule update --init --recursive
          cd submodules 

      - name: Set up Flutter in Submodule
        run: |
          flutter pub get
      - name: Run Flutter App on Emulator
        run: flutter run

      - name : return to main repository
        run: cd ..
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2

      - name: Start Appium server
        run:  |
          appium --log-level info --log-timestamp --address 127.0.0.1 --port 4723 --allow-insecure chromedriver_autodownload &
          sleep 5
      - name: Install Dependencies
        run: |
          npm ci











































































      - name: Install Dependencies
        run: |
          npm ci

      - name: Start appium server
        run:  |
          appium --log-level info --log-timestamp --address 127.0.0.1 --port 4723 --allow-insecure chromedriver_autodownload &
          sleep 5    
      - name: Run Tests
        run: |
          npm wdio
          # Add your test commands here to test the installed Flutter app